# Generated by Django 5.2.13 on 2026-09-24 14:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chatting", "0011_message_types_vote_payment_anon_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("store_name", models.CharField(max_length=100, verbose_name="식당")),
                (
                    "place_name",
                    models.CharField(max_length=100, verbose_name="배달 받을 장소"),
                ),
                (
                    "place_detail",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="상세 위치"
                    ),
                ),
                (
                    "min_order_amount",
                    models.PositiveIntegerField(verbose_name="최소 주문 금액"),
                ),
                (
                    "max_participants",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True, verbose_name="최대 인원"
                    ),
                ),
                (
                    "recruit_minutes",
                    models.PositiveSmallIntegerField(verbose_name="모집 시간(분)"),
                ),
                (
                    "deadline_at",
                    models.DateTimeField(db_index=True, verbose_name="모집 마감 시각"),
                ),
                (
                    "decision_deadline_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="방장 결정 마감 시각",
                    ),
                ),
                (
                    "memo",
                    models.TextField(blank=True, default="", verbose_name="방장 메모"),
                ),
                (
                    "order_link",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="함께주문 링크",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECRUITING", "RECRUITING"),
                            ("WAITING_DECISION", "WAITING_DECISION"),
                            ("ORDERED", "ORDERED"),
                            ("ARRIVED", "ARRIVED"),
                            ("SETTLED", "SETTLED"),
                            ("CANCELED", "CANCELED"),
                        ],
                        db_index=True,
                        default="RECRUITING",
                        max_length=20,
                        verbose_name="진행 상태",
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[("HOST", "HOST"), ("NO_DECISION", "NO_DECISION")],
                        default="",
                        max_length=20,
                        verbose_name="취소 사유",
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="주문 확정 시각",
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="도착 시각"
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="정산 완료 시각",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="취소 시각"
                    ),
                ),
                (
                    "chat_room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_party",
                        to="chatting.chatroom",
                        verbose_name="배달 채팅방",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_delivery_parties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="방장",
                    ),
                ),
                (
                    "payment_request",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_party",
                        to="chatting.chatpaymentrequest",
                        verbose_name="정산 요청",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="메뉴명"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="금액")),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="주문 취소 시각",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_order",
                        to="chatting.chatmessage",
                        verbose_name="주문 메시지",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주문한 유저",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="delivery.deliveryparty",
                        verbose_name="배달방",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryPenalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("until", models.DateTimeField(verbose_name="방 개설 금지 해제 시각")),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="delivery.deliveryparty",
                        verbose_name="패널티 원인 배달방",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_penalties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="패널티 받은 유저",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
