# Generated by Django 5.2.13 on 2026-05-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_id", models.PositiveIntegerField(verbose_name="major_id")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
            ],
            options={
                "verbose_name": "학과 게시판",
                "verbose_name_plural": "학과 게시판 목록",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("major_id",), name="major_unique_id"
                    )
                ],
            },
        ),
    ]
