# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "std_dept_id",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="std_dept_id",
                    ),
                ),
                (
                    "major_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="학과 이름"
                    ),
                ),
                (
                    "major_name_eng",
                    models.CharField(
                        max_length=100, null=True, verbose_name="학과 이름(영문)"
                    ),
                ),
                (
                    "major_dept_location",
                    models.CharField(
                        max_length=100, null=True, verbose_name="학과 건물 위치"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
            ],
            options={
                "verbose_name": "학과 게시판",
                "verbose_name_plural": "학과 게시판 목록",
            },
        ),
    ]
