# Generated by Django 5.2.13 on 2026-07-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="major",
            name="major_dept_location",
            field=models.CharField(
                max_length=100, null=True, verbose_name="학과 건물 위치"
            ),
        ),
        migrations.AddField(
            model_name="major",
            name="major_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="학과 이름"
            ),
        ),
        migrations.AddField(
            model_name="major",
            name="major_name_eng",
            field=models.CharField(
                max_length=100, null=True, verbose_name="학과 이름(영문)"
            ),
        ),
    ]
