# Generated by Django 5.2.13 on 2026-07-20 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMajor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가 시간"),
                ),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_additions",
                        to="major.major",
                        verbose_name="추가한 학과 게시판",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="major_additions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "학과 게시판 추가",
                "verbose_name_plural": "학과 게시판 추가 목록",
            },
        ),
        migrations.AddField(
            model_name="major",
            name="readers",
            field=models.ManyToManyField(
                related_name="added_majors",
                through="major.UserMajor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="추가한 유저들",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermajor",
            constraint=models.UniqueConstraint(
                fields=("user", "major"), name="usermajor_unique"
            ),
        ),
    ]
