# Generated by Django 5.2.13 on 2026-07-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0002_usermajor_major_readers_usermajor_usermajor_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="major",
            name="major_code",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="학과 코드"
            ),
        ),
    ]
