version: "3"

services:
  api:
    image: newara
    depends_on:
      - celery
      - db
      - redis
      - elastic
    environment:
      - DJANGO_SETTINGS_MODULE=ara.settings.test
      - DJANGO_ENV=${DJANGO_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - AWS_BUCKET_NAME=sparcs-newara-dev
      - AWS_BUCKET_NAME_STATIC=sparcs-kaist-ara-beta-static
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SSO_CLIENT_ID=${SSO_CLIENT_ID}
      - SSO_SECRET_KEY=${SSO_SECRET_KEY}
      - NEWARA_DB_HOST=db
      - NEWARA_DB_PORT=3306
      - NEWARA_DB_USER=root
      - NEWARA_DB_PASSWORD=root-password
      - NEWARA_DB_NAME=new_ara
      - NEWARA_REDIS_ADDRESS=redis
      - NEWARA_REDIS_PORT=6379
      - NEWARA_ELASTICSEARCH_HOST=elastic
      - NEWARA_ELASTICSEARCH_PORT=9200
    entrypoint: /newara/www/.docker/run.sh

  celery:
    image: newara
    depends_on:
      - db
      - redis
      - elastic
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings.test
      - DJANGO_ENV=${DJANGO_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - AWS_BUCKET_NAME=sparcs-newara-dev
      - AWS_BUCKET_NAME_STATIC=sparcs-kaist-ara-beta-static
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SSO_CLIENT_ID=${SSO_CLIENT_ID}
      - SSO_SECRET_KEY=${SSO_SECRET_KEY}
      - NEWARA_DB_HOST=db
      - NEWARA_DB_PORT=3306
      - NEWARA_DB_USER=root
      - NEWARA_DB_PASSWORD=root-password
      - NEWARA_DB_NAME=new_ara
      - NEWARA_REDIS_ADDRESS=redis
      - NEWARA_REDIS_PORT=6379
      - NEWARA_ELASTICSEARCH_HOST=elastic
      - NEWARA_ELASTICSEARCH_PORT=9200
      - C_FORCE_ROOT=true
    entrypoint: /newara/www/.docker/run-celery.sh

  db:
    image: mysql:8
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=new_ara
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:6
    expose:
      - 6379

  elastic:
    image: elasticsearch:7.9.2
    expose:
      - 9200
    environment:
      - discovery.type=single-node
    command: >
      bash -c "bin/elasticsearch-plugin list | grep -q analysis-nori || bin/elasticsearch-plugin install --batch analysis-nori
      && /usr/local/bin/docker-entrypoint.sh"
