# Check S3 'sparcs-credentials' bucket for the complete file
version: '3'

services:
  api:
    container_name: newara
    image: newara:local
    tty: false
    depends_on:
      - db
      - redis
      - celery_worker
      - elasticsearch
    ports:
      - 9000:9000
    environment:
      - DJANGO_ENV=development
      - SECRET_KEY=
      - AWS_BUCKET_NAME=sparcs-newara
      - AWS_BUCKET_NAME_STATIC=sparcs-kaist-ara-beta-static
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - SSO_CLIENT_ID=
      - SSO_SECRET_KEY=
      - SENTRY_DSN=
      - NEWARA_DB_HOST=db
      - NEWARA_DB_PORT=3306
      - NEWARA_DB_USER=root
      - NEWARA_DB_PASSWORD=
      - NEWARA_DB_NAME=new_ara
      - NEWARA_REDIS_ADDRESS=redis
      - PORTAL_ID=
      - PORTAL_PASSWORD=
      - NEWARA_ELASTICSEARCH_HOST=elasticsearch
      - NEWARA_ELASTICSEARCH_PORT=9200
      - HASH_SECRET_VALUE=1
      - PORTAL_2FA_KEY=
    entrypoint: /newara/www/.docker/run.sh
    volumes:
      - /var/log/newara_api:/var/log/newara
      - nori:/newara/www/ara/db/elasticsearch

  celery_worker:
    image: newara:local
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_ENV=development
      - SECRET_KEY=
      - AWS_BUCKET_NAME=sparcs-newara
      - AWS_BUCKET_NAME_STATIC=sparcs-kaist-ara-beta-static
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - SSO_CLIENT_ID=
      - SSO_SECRET_KEY=
      - SENTRY_DSN=
      - NEWARA_DB_HOST=db
      - NEWARA_DB_PORT=3306
      - NEWARA_DB_USER=root
      - NEWARA_DB_PASSWORD=
      - NEWARA_DB_NAME=new_ara
      - NEWARA_REDIS_ADDRESS=redis
      - PORTAL_ID=
      - PORTAL_PASSWORD=
      - NEWARA_ELASTICSEARCH_HOST=elasticsearch
      - NEWARA_ELASTICSEARCH_PORT=9200
      - C_FORCE_ROOT=true
      - HASH_SECRET_VALUE=1
      - PORTAL_2FA_KEY=
    entrypoint: /newara/www/.docker/run-celery.sh
    volumes:
      - /var/log/newara_celery:/var/log/newara

  db:
    container_name: db
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=new_ara
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci

  redis:
    image: redis:6
    expose:
      - 6379

  elasticsearch:
    image: elasticsearch:7.9.2
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
    command: bash -c "
      bin/elasticsearch-plugin list | grep -q analysis-nori || bin/elasticsearch-plugin install --batch analysis-nori
      && /usr/local/bin/docker-entrypoint.sh
      "
    volumes:
      - nori:/usr/share/elasticsearch/config/analysis

volumes:
  nori:
