# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-23 04:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간')),
                ('uid', models.CharField(max_length=30, verbose_name='Sparcs SSO uid')),
                ('sid', models.CharField(max_length=30, verbose_name='Sparcs SSO sid')),
                ('sso_user_info', django_mysql.models.JSONField(default=dict, verbose_name='Sparcs SSO 정보')),
                ('picture', models.ImageField(default=None, null=True, upload_to='user_profiles/pictures', verbose_name='프로필')),
                ('nickname', models.CharField(blank=True, default='', max_length=128, verbose_name='닉네임')),
                ('see_sexual', models.BooleanField(default=False, verbose_name='성인/음란성 보기')),
                ('see_social', models.BooleanField(default=False, verbose_name='정치/사회성 보기')),
                ('extra_preferences', django_mysql.models.JSONField(default=dict, verbose_name='기타 설정')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '유저 프로필',
                'verbose_name_plural': '유저 프로필 목록',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('nickname', 'deleted_at')]),
        ),
    ]
