apiVersion: v1
kind: ConfigMap
metadata:
  name: ara-env
data:
  SSO_CLIENT_ID: "test00256eed00703a1485de"
  DJANGO_ENV: "development"
  C_FORCE_ROOT: "true"
  AWS_BUCKET_NAME: "sparcs-newara-dev"
  AWS_BUCKET_NAME_STATIC: "sparcs-kaist-ara-beta-static"
  AWS_ACCESS_KEY_ID: "AKIAZWM3SVKMGCVAUUA3"
