apiVersion: apps/v1
kind: Deployment
metadata:
  name: ara-server
  labels:
    app: ara-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ara-server
  template:
    metadata:
      labels:
        app: ara-server
    spec:
      containers:
        - name: ara-server
          image: 666583083672.dkr.ecr.ap-northeast-2.amazonaws.com/newara:v3.0.1
          command: ["/newara/www/.docker/run.sh"]
          ports:
          - containerPort: 9000
          envFrom:
          - secretRef:
              name: ara-secret
          env:
          - name: SSO_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: SSO_CLIENT_ID
          - name: DJANGO_ENV
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: DJANGO_ENV
          - name: AWS_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: AWS_BUCKET_NAME
          - name: AWS_BUCKET_NAME_STATIC
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: AWS_BUCKET_NAME_STATIC
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: AWS_ACCESS_KEY_ID
          - name: NEWARA_REDIS_ADDRESS
            value: "ara-redis-service"
