apiVersion: apps/v1
kind: Deployment
metadata:
  name: ara-server
  labels:
    app: ara-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ara-server
  template:
    metadata:
      labels:
        app: ara-server
    spec:
      containers:
        - name: ara-server
          image: 666583083672.dkr.ecr.ap-northeast-2.amazonaws.com/newara:prod
          command: ["/newara/www/.docker/run.sh"]
          ports:
          - containerPort: 9000
          envFrom:
          - secretRef:
              name: ara-secret
          env:
          - name: SSO_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: SSO_CLIENT_ID
          - name: PORTAL_ID
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: PORTAL_ID
          - name: SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: SENTRY_DSN
          - name: DJANGO_ENV
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: DJANGO_ENV
          - name: AWS_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: AWS_BUCKET_NAME
          - name: AWS_BUCKET_NAME_STATIC
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: AWS_BUCKET_NAME_STATIC
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: AWS_ACCESS_KEY_ID
          - name: NEWARA_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: NEWARA_DB_HOST
          - name: NEWARA_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: NEWARA_DB_PORT
          - name: NEWARA_DB_USER
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: NEWARA_DB_USER
          - name: NEWARA_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: NEWARA_DB_NAME
          - name: NEWARA_ELASTICSEARCH_HOST
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: NEWARA_ELASTICSEARCH_HOST
          - name: NEWARA_ELASTICSEARCH_PORT
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: NEWARA_ELASTICSEARCH_PORT
          - name: HASH_SECRET_VALUE
            valueFrom:
              configMapKeyRef:
                name: ara-env
                key: HASH_SECRET_VALUE
          - name: REDIS_HOST
            value: "ara-redis-service"
          volumeMounts:
          - mountPath: "/newara/www"
            name: firebase
            readOnly: true
      volumes:
        - name: firebase
          secret:
            secretName: firebase-credentials