apiVersion: v1
kind: Secret
metadata:
  name: ara-secret
  namespace: ara
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: base64encoded
  SENTRY_DSN: base64encoded
  SECRET_KEY: base64encoded
  HASH_SECRET_VALUE: base64encoded
  NEWARA_DB_USER: base64encoded
  NEWARA_DB_PASSWORD: base64encoded
  NEWARA_ELASTICSEARCH_URL: base64encoded
  PORTAL_JSESSIONID: base64encoded
  SSO_SECRET_KEY: base64encoded
