apiVersion: v1
kind: Service
metadata:
  name: ara-redis-service
spec:
  selector:
    app: ara-redis
  ports:
  - name: ara-redis-service-port
    protocol: TCP
    port: 6379
    targetPort: ara-redis-port
