# Generated by Django 5.2.13 on 2026-05-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_courseenrollment_softdelete"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(max_length=16, verbose_name="과목 코드"),
                ),
                (
                    "professors_key",
                    models.CharField(max_length=128, verbose_name="교수 집합 키"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="대표 과목명")),
            ],
            options={
                "verbose_name": "과목 그룹",
                "verbose_name_plural": "과목 그룹 목록",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course_code", "professors_key"),
                        name="coursegroup_unique_code_profs",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="course.coursegroup",
                verbose_name="과목 그룹",
            ),
        ),
    ]
