# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_allow_regular_course_articles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseGroupingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        help_text="예: MAS101. 대소문자와 앞뒤 공백은 저장 시 정규화됩니다.",
                        max_length=16,
                        unique=True,
                        verbose_name="과목 코드",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            (
                                "CODE_AND_PROFESSORS",
                                "과목 코드 + 교수 집합 (기본)",
                            ),
                            ("COURSE_CODE", "과목 코드만 (교수 무시)"),
                        ],
                        default="CODE_AND_PROFESSORS",
                        max_length=32,
                        verbose_name="그룹 정책",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="예외 처리 이유와 관련 기획·운영 맥락을 기록합니다.",
                        verbose_name="적용 사유",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
            ],
            options={
                "verbose_name": "과목 그룹 예외 규칙",
                "verbose_name_plural": "과목 그룹 예외 규칙 목록",
                "ordering": ("course_code",),
            },
        ),
    ]
