# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 02:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OldAraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간')),
                ('username', models.CharField(db_index=True, max_length=160, verbose_name='아이디')),
                ('password', models.CharField(max_length=200, verbose_name='패스워드')),
                ('nickname', models.CharField(max_length=160, verbose_name='닉네임')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간')),
                ('sid', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='user_profiles/pictures', verbose_name='프로필')),
                ('nickname', models.CharField(blank=True, default='', max_length=128, verbose_name='닉네임')),
                ('signature', models.TextField(blank=True, default='', verbose_name='서명')),
                ('see_sexual', models.BooleanField(default=False, verbose_name='성인/음란성 보기')),
                ('see_social', models.BooleanField(default=False, verbose_name='정치/사회성 보기')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
