# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='', verbose_name='프로필'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='see_sexual',
            field=models.BooleanField(default=False, verbose_name='성인/음란성 보기'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='see_social',
            field=models.BooleanField(default=False, verbose_name='정치/사회성 보기'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(default='', verbose_name='서명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(default='', max_length=128, verbose_name='닉네임'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
