# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-20 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_userprofile_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldarauser',
            options={'ordering': ('-created_at',), 'verbose_name': '기존 사용자', 'verbose_name_plural': '기존 사용자 목록'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-created_at',), 'verbose_name': '유저 프로필', 'verbose_name_plural': '유저 프로필 목록'},
        ),
    ]
