# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20171201_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='프로필'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(blank=True, verbose_name='서명'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=128, verbose_name='닉네임'),
        ),
    ]
