# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-31 21:38
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20180620_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_preferences',
            field=django_mysql.models.JSONField(default=dict, verbose_name='기타 설정'),
        ),
    ]
