# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-10 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_userprofile_extra_preferences'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('nickname', 'deleted_at')]),
        ),
    ]
