# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-10 21:46
from __future__ import unicode_literals

import uuid

from django.db import migrations


def set_nickname_default_value(apps, schema_editor):
    user_profile_model = apps.get_model('session', 'UserProfile')

    for user_profile in user_profile_model.objects.all():
        if not user_profile.nickname:
            user_profile.nickname = str(uuid.uuid4())
            user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_userprofile_extra_preferences'),
    ]

    operations = [
        migrations.RunPython(set_nickname_default_value),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('nickname', 'deleted_at')]),
        ),
    ]
