# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20180405_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_nickname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
