# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20180428_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user_profiles/pictures', verbose_name='프로필'),
        ),
    ]
