# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20180428_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldAraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('username', models.CharField(db_index=True, max_length=160, verbose_name='아이디')),
                ('password', models.CharField(max_length=200, verbose_name='패스워드')),
                ('nickname', models.CharField(max_length=160, verbose_name='닉네임')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
