# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-02 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_oldarauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldarauser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='oldarauser',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='oldarauser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
    ]
