# Generated by Django 2.2.14 on 2020-07-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190920_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='past_user',
            field=models.BooleanField(default=False, verbose_name='이전 사용자'),
        ),
    ]
