# Generated by Django 2.2.12 on 2020-08-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190920_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='최근 닉네임 변경일시'),
        ),
    ]
