# Generated by Django 2.2.15 on 2020-08-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile_is_kaist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="생성 시간"
            ),
        ),
    ]
