# Generated by Django 2.2.14 on 2020-07-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_past_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('uid', 'deleted_at'), ('nickname', 'past_user', 'deleted_at'), ('sid', 'deleted_at')},
        ),
    ]
