# Generated by Django 2.2.15 on 2020-08-20 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_created_at_to_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname_updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='최근 닉네임 변경일시'),
        ),
    ]
