# Generated by Django 2.2.14 on 2020-07-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ara_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='이전 아라 아이디'),
        ),
    ]
