# Generated by Django 2.2.14 on 2020-08-06 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_ara_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
    ]
