# Generated by Django 3.1 on 2020-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_manual_user_org_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualuser",
            name="sso_email",
            field=models.EmailField(
                max_length=160, unique=True, verbose_name="sso 이메일"
            ),
        ),
    ]
