# Generated by Django 3.2.9 on 2022-03-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_set_created_at_to_timezone_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='공식 계정'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_school_admin',
            field=models.BooleanField(default=False, verbose_name='학교 관리자'),
        ),
    ]
