# Generated by Django 3.2.16 on 2022-11-01 20:29

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0017_add_user_group_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        verbose_name="토큰",
                    ),
                ),
                (
                    "last_activated_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="최근 토큰 부여 및 확인 시간"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_token_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM 토큰",
                "verbose_name_plural": "FCM 푸시알림 토큰",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
