# Generated by Django 3.2.16 on 2022-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_fcmtoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fcmtoken",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="fcmtoken",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="fcmtoken",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="fcmtoken",
            name="is_web",
            field=models.BooleanField(
                db_index=True,
                default=True,
                max_length=100,
                verbose_name="토큰 부여 플랫폼이 웹인지 여부",
            ),
        ),
    ]
