# Generated by Django 3.2.16 on 2022-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_fcmtoken_hard_delete_is_web"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmtoken",
            name="is_web",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="토큰 부여 플랫폼이 웹인지 여부"
            ),
        ),
    ]
