# Generated by Django 4.2.3 on 2023-07-12 02:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_after_fcmtoken_is_web"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="extra_preferences",
        ),
    ]
