# Generated by Django 4.2.3 on 2023-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_after_fcmtoken_is_web"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="extra_preferences",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sso_user_info",
            field=models.JSONField(editable=False, verbose_name="Sparcs SSO 정보"),
        ),
    ]
