# Generated by Django 4.2.3 on 2023-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_remove_userprofile_extra_preferences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="sso_user_info",
            field=models.JSONField(
                default=dict, editable=False, verbose_name="Sparcs SSO 정보"
            ),
        ),
    ]
