# Generated by Django 2.2.7 on 2020-03-25 20:09

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20190926_2222"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(1, 1, 1, 0, 0), verbose_name="생성 시간"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=datetime.datetime(1, 1, 1, 0, 0), verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=datetime.datetime(1, 1, 1, 0, 0), verbose_name="삭제 시간"
                    ),
                ),
                (
                    "ko_question",
                    models.CharField(max_length=32, verbose_name="FAQ 국문 질문"),
                ),
                (
                    "en_question",
                    models.CharField(max_length=32, verbose_name="FAQ 영문 질문"),
                ),
                ("ko_answer", models.TextField(verbose_name="FAQ 국문 답변")),
                ("en_answer", models.TextField(verbose_name="FAQ 영문 답변")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ 목록",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
