# Generated by Django 2.2.14 on 2020-07-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_FAQ"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.TextField(default=None, null=True, verbose_name="링크"),
        ),
    ]
