# Generated by Django 2.2.15 on 2020-08-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_metadatamodel_db_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_set', to='core.Article', verbose_name='문서'),
        ),
    ]
