# Generated by Django 2.2.12 on 2020-08-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_metadatamodel_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_kaist',
            field=models.BooleanField(default=False, verbose_name='카이스트 구성원 전용 게시판'),
        ),
    ]
