# Generated by Django 3.1 on 2020-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_related_name_for_cascade_deletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="mimetype",
            field=models.CharField(
                default="text/plain", max_length=128, verbose_name="타입"
            ),
        ),
    ]
