# Generated by Django 3.2.4 on 2021-11-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_set_created_at_to_timezone_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_anonymous",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="게시판의 글과 댓글들이 익명이도록 합니다.",
                verbose_name="익명 게시판",
            ),
        ),
    ]
