# Generated by Django 3.2.9 on 2022-02-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_board_is_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="group_id",
            field=models.IntegerField(default=1, verbose_name="그룹 ID"),
        ),
    ]
