# Generated by Django 3.2.9 on 2022-05-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_communication_article_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communicationarticle",
            name="confirmed_by_school_at",
        ),
    ]
