# Generated by Django 3.2.9 on 2022-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_communication_article_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='access_mask',
        ),
        migrations.AddField(
            model_name='board',
            name='read_access_mask',
            field=models.SmallIntegerField(default=222, verbose_name='읽기 권한'),
        ),
        migrations.AddField(
            model_name='board',
            name='write_access_mask',
            field=models.SmallIntegerField(default=218, verbose_name='쓰기 권한'),
        ),
    ]
