# Generated by Django 3.2.9 on 2022-04-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_communicationarticle_school_response_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationarticle',
            name='id',
        ),
        migrations.AlterField(
            model_name='communicationarticle',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='communication_article', serialize=False, to='core.article', verbose_name='게시물'),
        ),
    ]
