# Generated by Django 3.2.9 on 2022-04-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_is_anonymous_to_name_type'),
        ('core', '0040_communicationarticle_school_response_status'),
    ]

    operations = [
    ]
