# Generated by Django 3.2.9 on 2022-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_communication_article_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='access_mask',
            field=models.IntegerField(default=223, verbose_name='접근 권한 값'),
        ),
    ]
