# Generated by Django 3.2.9 on 2022-08-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_read_write_access_masks'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='comment_access_mask',
            field=models.SmallIntegerField(default=254, verbose_name='댓글 권한'),
        ),
    ]
