# Generated by Django 3.2.9 on 2022-04-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20220426_0146'),
        ('core', '0042_alter_board_access_mask'),
    ]

    operations = [
    ]
