# Generated by Django 3.2.16 on 2023-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_board_comment_access_mask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(
                blank=True, default=None, null=True, verbose_name="포탈 링크"
            ),
        ),
    ]
