# Generated by Django 3.2.16 on 2022-11-10 17:50

from django.db import migrations, models

import apps.core.models.attachment


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_board_comment_access_mask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                max_length=200,
                upload_to=apps.core.models.attachment.Attachment._hash_filename,
                verbose_name="링크",
            ),
        ),
    ]
