# Generated by Django 3.2.16 on 2023-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_portalviewcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalviewcount',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='article',
            name='latest_portal_view_count',
            field=models.IntegerField(null=True, verbose_name='포탈조회수'),
        ),
    ]
