# Generated by Django 3.2.16 on 2023-03-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_article_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="hidden_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="숨김 시간"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="hidden_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="숨김 시간"
            ),
        ),
    ]
