# Generated by yuwol

from django.db import migrations

from ara.settings import MIN_TIME


def update_hidden_at(apps, schema_editor):
    Article = apps.get_model("core", "Article")
    Article.objects.filter(hidden_at=MIN_TIME).update(hidden_at=None)

    Comment = apps.get_model("core", "Comment")
    Comment.objects.filter(hidden_at=MIN_TIME).update(hidden_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_hidden_at_to_nullable"),
    ]

    operations = [
        migrations.RunPython(update_hidden_at, atomic=True),
    ]
