# Generated by Django 3.2.16 on 2023-03-16 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_article_add_latest_portal_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='latest_portal_view_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='포탈조회수'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, db_index=True, default=None, max_length=256, null=True, verbose_name='링크'),
        ),
        migrations.AlterField(
            model_name='portalviewcount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시간'),
        ),
    ]
