# Generated by Django 3.2.16 on 2023-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_update_hidden_at_min_time_to_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="topped_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="인기글 달성 시각"
            ),
        ),
    ]
