# Generated by Django 3.2.16 on 2023-05-09 13:57

import apps.core.models.board
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_update_hidden_at_min_time_to_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="name_type",
            field=models.SmallIntegerField(
                db_index=True,
                default=apps.core.models.board.NameType["REGULAR"],
                help_text="글과 댓글을 어떤 이름 설정(닉네임/익명/실명)으로 작성할 수 있는지 정의합니다.",
                verbose_name="닉네임/익명/실명글 허용 여부 설정",
            ),
        ),
    ]
