# Generated by Django 3.2.16 on 2023-05-09 14:03

from django.db import migrations

from apps.core.models.board import Board, NameType
from apps.core.models.article import Article
from apps.core.models.comment import Comment


def update_nametypes(apps, schema_editor):
    regular_boards = Board.objects.filter(name_type=0).values()
    anonymous_boards = Board.objects.filter(name_type=1).values()
    realname_boards = Board.objects.filter(name_type=2).values()

    realname_boards.update(name_type=NameType.REALNAME)
    anonymous_boards.update(name_type=NameType.ANONYMOUS)
    regular_boards.update(name_type=NameType.REGULAR)

    regular_articles = Article.objects.filter(name_type=0).values()
    anonymous_articles = Article.objects.filter(name_type=1).values()
    realname_articles = Article.objects.filter(name_type=2).values()

    realname_articles.update(name_type=NameType.REALNAME)
    anonymous_articles.update(name_type=NameType.ANONYMOUS)
    regular_articles.update(name_type=NameType.REGULAR)

    regular_comments = Comment.objects.filter(name_type=0).values()
    anonymous_comments = Comment.objects.filter(name_type=1).values()
    realname_comments = Comment.objects.filter(name_type=2).values()

    realname_comments.update(name_type=NameType.REALNAME)
    anonymous_comments.update(name_type=NameType.ANONYMOUS)
    regular_comments.update(name_type=NameType.REGULAR)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_board_name_type"),
    ]

    operations = [migrations.RunPython(update_nametypes)]
