# Generated by Django 4.2.3 on 2023-07-17 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_board_top_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="en_description",
        ),
        migrations.RemoveField(
            model_name="board",
            name="ko_description",
        ),
    ]
