# Generated by Django 4.2.3 on 2023-07-21 04:48

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_remove_board_en_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["en_name"], unique=True
            ),
        ),
    ]
