# Generated by Django 4.2.3 on 2023-07-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_board_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="banner_url",
        ),
        migrations.AlterField(
            model_name="board",
            name="en_banner_description",
            field=models.TextField(
                blank=True, default="", verbose_name="게시판 배너에 삽입되는 영문 소개"
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="ko_banner_description",
            field=models.TextField(
                blank=True, default="", verbose_name="게시판 배너에 삽입되는 국문 소개"
            ),
        ),
    ]
