# Generated by Django 4.2.3 on 2023-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_remove_board_banner_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ko_name",
                    models.CharField(max_length=64, verbose_name="게시판 그룹 국문 이름"),
                ),
                (
                    "en_name",
                    models.CharField(max_length=64, verbose_name="게시판 그룹 영문 이름"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=32, unique=True, verbose_name="슬러그"),
                ),
            ],
            options={
                "verbose_name": "게시판 그룹",
                "verbose_name_plural": "게시판 그룹 목록",
            },
        ),
    ]
