# Generated by Django 4.2.3 on 2023-07-31 12:00

import apps.core.models.board
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_remove_board_group_id_board_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="comment_count",
            field=models.PositiveIntegerField(default=0, verbose_name="댓글 수"),
        ),
        migrations.AlterField(
            model_name="article",
            name="hit_count",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AlterField(
            model_name="article",
            name="migrated_hit_count",
            field=models.PositiveIntegerField(default=0, verbose_name="이전된 조회수"),
        ),
        migrations.AlterField(
            model_name="article",
            name="migrated_negative_vote_count",
            field=models.PositiveIntegerField(default=0, verbose_name="이전된 싫어요 수"),
        ),
        migrations.AlterField(
            model_name="article",
            name="migrated_positive_vote_count",
            field=models.PositiveIntegerField(default=0, verbose_name="이전된 좋아요 수"),
        ),
        migrations.AlterField(
            model_name="article",
            name="name_type",
            field=models.PositiveSmallIntegerField(
                default=apps.core.models.board.NameType["REGULAR"],
                verbose_name="익명 혹은 실명 여부",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="negative_vote_count",
            field=models.PositiveIntegerField(default=0, verbose_name="싫어요 수"),
        ),
        migrations.AlterField(
            model_name="article",
            name="positive_vote_count",
            field=models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.AlterField(
            model_name="article",
            name="report_count",
            field=models.PositiveIntegerField(default=0, verbose_name="신고 수"),
        ),
        migrations.AlterField(
            model_name="board",
            name="top_threshold",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="인기글 달성 기준 좋아요 개수"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="negative_vote_count",
            field=models.PositiveIntegerField(default=0, verbose_name="싫어요 수"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="positive_vote_count",
            field=models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="report_count",
            field=models.PositiveIntegerField(default=0, verbose_name="신고 수"),
        ),
    ]
