# Generated by Django 4.2.5 on 2023-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_alter_article_comment_count_alter_article_hit_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("default", "default"),
                    ("article_commented", "article_commented"),
                    ("comment_commented", "comment_commented"),
                    ("article_new", "article_new"),
                ],
                default="default",
                max_length=32,
                verbose_name="알림 종류",
            ),
        ),
    ]
