# Generated by Django 4.2.3 on 2024-01-10 17:16

import django.db.models.deletion
from django.db import migrations, models

from apps.core.models import BoardAccessPermissionType


def move_board_permissions(apps, schema_editor):
    Board = apps.get_model("core", "Board")
    BoardPermission = apps.get_model("core", "BoardPermission")
    Group = apps.get_model("user", "Group")
    for board in Board.objects.all():
        read_access_mask = board.read_access_mask
        write_access_mask = board.write_access_mask
        comment_access_mask = board.comment_access_mask

        for group in Group.objects.all():
            read = bool((read_access_mask & (1 << (group.group_id - 1))) > 0)
            write = bool((write_access_mask & (1 << (group.group_id - 1))) > 0)
            comment = bool((comment_access_mask & (1 << (group.group_id - 1))) > 0)

            if read:
                BoardPermission.objects.create(
                    board=board,
                    group=group,
                    permission=BoardAccessPermissionType.READ,
                )
            if write:
                BoardPermission.objects.create(
                    board=board,
                    group=group,
                    permission=BoardAccessPermissionType.WRITE,
                )
            if comment:
                BoardPermission.objects.create(
                    board=board,
                    group=group,
                    permission=BoardAccessPermissionType.COMMENT,
                )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_group_remove_userprofile_group_and_more"),
        ("core", "0057_alter_article_name_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission", models.SmallIntegerField(verbose_name="permission")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.board",
                        verbose_name="board slug",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.group",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "BoardPermission",
                "verbose_name_plural": "BoardPermissions",
                "unique_together": {("group", "board", "permission")},
            },
        ),
        migrations.RunPython(move_board_permissions),
        migrations.RemoveField(
            model_name="board",
            name="comment_access_mask",
        ),
        migrations.RemoveField(
            model_name="board",
            name="read_access_mask",
        ),
        migrations.RemoveField(
            model_name="board",
            name="write_access_mask",
        ),
    ]
