# Generated by Django 4.2.9 on 2024-03-06 07:05

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_article_name_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="latest_portal_view_count",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="포탈 조회수"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(
                blank=True,
                db_index=True,
                default=None,
                max_length=256,
                null=True,
                verbose_name="포탈 링크",
            ),
        ),
        migrations.CreateModel(
            name="PortalViewCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="게시물",
                        to="core.article",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
