# Generated by Django 4.2.7 on 2024-01-09 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_alter_portal_crawl_related_field"),
        ("core", "0057_alter_article_name_type_and_more"),
    ]

    operations = []
