# Generated by Django 4.2.9 on 2024-02-06 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_notification_type"),
        ("core", "0058_merge_20240109_2331"),
    ]

    operations = []
