# Generated by Django 4.2.11 on 2024-11-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_article_latest_portal_view_count_alter_article_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="topped_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="인기글 달성 시각",
            ),
        ),
    ]
