# Generated by Django 4.2.23 on 2025-07-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0008_chatroom_picture"),
        ("core", "0058_article_latest_portal_view_count_alter_article_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_chat_room",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_set",
                to="chatting.chatroom",
                verbose_name="알림 관련 채팅방",
            ),
        ),
    ]
