# Generated by Django 4.2.9 on 2024-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_merge_20240206_2234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(
                blank=True,
                db_index=True,
                default=None,
                max_length=256,
                null=True,
                verbose_name="포탈 링크",
            ),
        ),
    ]
