# Generated by Django 4.2.23 on 2025-08-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_articlemetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="type",
            field=models.CharField(
                choices=[("TEXT", "TEXT"), ("IMAGE", "IMAGE"), ("FILE", "FILE")],
                default="TEXT",
                max_length=20,
                verbose_name="댓글 타입",
            ),
        ),
    ]
