# Generated by Django 4.2.23 on 2026-02-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_comment_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['name_type', 'deleted_at', '-created_at'], name='idx_article_list_speedup'),
        ),
    ]
