# Generated by Django 4.2.23 on 2026-02-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_article_idx_article_list_speedup'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='idx_article_list_speedup',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['name_type', '-created_at', 'deleted_at'], name='idx_article_list_query'),
        ),
    ]
