# Generated by Django 4.2.23 on 2026-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_article_idx_article_list_speedup_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='idx_article_list_query',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['name_type', '-created_at'], name='idx_article_list_query'),
        ),
    ]
