# Generated by Django 4.2.23 on 2026-02-19 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_article_idx_article_list_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='삭제 시간'),
        ),
    ]
