# Generated by Django 5.2.11 on 2026-04-05 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_article_id_alter_articledeletelog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='별칭'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=200, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'tar', 'gz', 'mp4', 'mp3'])], verbose_name='링크'),
        ),
    ]
