# Generated by Django 5.2.13 on 2026-05-14 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_article_related_course"),
        ("major", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="related_major",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="학과별 게시판 글일 때 set. 일반 글은 null.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_set",
                to="major.major",
                verbose_name="관련 학과 게시판",
            ),
        ),
    ]
