# Generated by Django 5.2.13 on 2026-05-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_article_related_major"),
        ("course", "0005_course_group_non_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="related_course_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="과목 게시판 글일 때 set. 학기 무관 누적 단위. 일반 글은 null.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_set",
                to="course.coursegroup",
                verbose_name="관련 과목 그룹 게시판",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="related_course",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="글이 작성된 학기 Course (출처). 게시판 묶음은 related_course_group 기준.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_set",
                to="course.course",
                verbose_name="관련 과목 게시판",
            ),
        ),
    ]
