# Generated by Django 5.2.13 on 2026-09-25 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0014_chatmessage_chat_msg_room_deleted_id"),
        ("core", "0072_backfill_article_course_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="chat_message",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_set",
                to="chatting.chatmessage",
                verbose_name="신고된 채팅 메시지",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_set",
                to="chatting.chatroom",
                verbose_name="신고된 채팅방",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_report_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="처리자",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reported_email",
            field=models.CharField(
                blank=True, default="", max_length=254, verbose_name="피신고자 이메일"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_report_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="피신고자",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reporter_email",
            field=models.CharField(
                blank=True, default="", max_length=254, verbose_name="신고자 이메일"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "접수"),
                    ("IN_PROGRESS", "처리 중"),
                    ("DONE", "처리 완료"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="처리 상태",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status_changed_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="상태 변경 시각"
            ),
        ),
    ]
