# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:19
from __future__ import unicode_literals

import apps.core.models.notification
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명')),
                ('is_content_sexual', models.BooleanField(default=False, verbose_name='성인/음란성 내용')),
                ('is_content_social', models.BooleanField(default=False, verbose_name='정치/사회성 내용')),
                ('use_signature', models.BooleanField(default=True, verbose_name='서명 사용')),
                ('hit_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('positive_vote_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('negative_vote_count', models.IntegerField(default=0, verbose_name='싫어요 수')),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서',
            },
        ),
        migrations.CreateModel(
            name='ArticleReadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_read_log_set', to='core.Article', verbose_name='조회된 게시글')),
                ('read_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_read_log_set', to=settings.AUTH_USER_MODEL, verbose_name='조회자')),
            ],
            options={
                'verbose_name': '게시물 조회 기록',
                'verbose_name_plural': '게시물 조회 기록',
            },
        ),
        migrations.CreateModel(
            name='ArticleUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('content', models.TextField(verbose_name='본문')),
                ('is_content_sexual', models.BooleanField(default=False, verbose_name='성인/음란성 내용')),
                ('is_content_social', models.BooleanField(default=False, verbose_name='정치/사회성 내용')),
                ('use_signature', models.BooleanField(default=True, verbose_name='서명 사용')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_update_log_set', to='core.Article', verbose_name='변경된 게시글')),
            ],
            options={
                'verbose_name': '게시물 변경 기록',
                'verbose_name_plural': '게시물 변경 기록',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('file', models.FileField(upload_to='', verbose_name='링크')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('black_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_set', to=settings.AUTH_USER_MODEL, verbose_name='차단한 사람')),
                ('black_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_set', to=settings.AUTH_USER_MODEL, verbose_name='차단당한 사람')),
            ],
            options={
                'verbose_name': '유저 간 차단',
                'verbose_name_plural': '유저 간 차단',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('ko_name', models.CharField(max_length=32, unique=True, verbose_name='게시판 국문 이름')),
                ('en_name', models.CharField(max_length=32, unique=True, verbose_name='게시판 영문 이름')),
                ('ko_description', models.TextField(verbose_name='게시판 국문 소개')),
                ('en_description', models.TextField(verbose_name='게시판 영문 소개')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('content', models.TextField(default=None, verbose_name='본문')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명')),
                ('use_signature', models.BooleanField(default=True, verbose_name='서명 사용')),
                ('positive_vote_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('negative_vote_count', models.IntegerField(default=0, verbose_name='싫어요 수')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Attachment', verbose_name='첨부 파일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent_article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='core.Article', verbose_name='글')),
                ('parent_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='core.Comment', verbose_name='댓글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
            },
        ),
        migrations.CreateModel(
            name='CommentUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('content', models.TextField(default=None, verbose_name='본문')),
                ('attachment', models.ImageField(default=None, upload_to='', verbose_name='첨부 그림')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_update_log_set', to='core.Comment', verbose_name='변경된 댓글')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_update_log_set', to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
            ],
            options={
                'verbose_name': '댓글 변경 기록',
                'verbose_name_plural': '댓글 변경 기록',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('data', django_mysql.models.JSONField(default=apps.core.models.notification.get_default_data, verbose_name='알림 JSON')),
                ('notification_type', models.CharField(choices=[('default', 'default')], max_length=256, verbose_name='알림 타입')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('parent_article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_set', to='core.Article', verbose_name='신고된 문서')),
                ('parent_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_set', to='core.Comment', verbose_name='신고된 댓글')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '신고',
                'verbose_name_plural': '신고',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('ko_name', models.CharField(max_length=32, unique=True, verbose_name='말머리 국문 이름')),
                ('en_name', models.CharField(max_length=32, unique=True, verbose_name='말머리 영문 이름')),
                ('ko_description', models.TextField(verbose_name='말머리 국문 소개')),
                ('en_description', models.TextField(verbose_name='말머리 영문 소개')),
                ('parent_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_set', to='core.Board', verbose_name='상위 게시판')),
            ],
            options={
                'verbose_name': '말머리',
                'verbose_name_plural': '말머리',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('is_positive', models.BooleanField(verbose_name='찬반')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='투표자')),
                ('parent_article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='core.Article', verbose_name='상위 문서')),
                ('parent_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='core.Comment', verbose_name='상위 댓글')),
            ],
            options={
                'verbose_name': '투표',
                'verbose_name_plural': '투표',
            },
        ),
        migrations.AddField(
            model_name='articleupdatelog',
            name='parent_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_update_log_set', to='core.Board', verbose_name='게시판'),
        ),
        migrations.AddField(
            model_name='articleupdatelog',
            name='parent_topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_update_log_set', to='core.Topic', verbose_name='말머리'),
        ),
        migrations.AddField(
            model_name='articleupdatelog',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_update_log_set', to=settings.AUTH_USER_MODEL, verbose_name='변경자'),
        ),
        migrations.AddField(
            model_name='article',
            name='attachments',
            field=models.ManyToManyField(blank=True, db_index=True, to='core.Attachment', verbose_name='첨부 파일(들)'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to='core.Board', verbose_name='게시판'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent_topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to='core.Topic', verbose_name='말머리'),
        ),
    ]
