# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('ko_name', models.CharField(max_length=32, unique=True, verbose_name='게시판 국문 이름')),
                ('en_name', models.CharField(max_length=32, unique=True, verbose_name='게시판 영문 이름')),
                ('ko_description', models.TextField(verbose_name='게시판 국문 소개')),
                ('en_description', models.TextField(verbose_name='게시판 영문 소개')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
            },
        ),
    ]
