# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_set', to='core.Article', verbose_name='글')),
                ('scrapped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_set', to=settings.AUTH_USER_MODEL, verbose_name='스크랩한 사람')),
            ],
            options={
                'verbose_name': '스크랩',
                'verbose_name_plural': '스크랩',
            },
        ),
    ]
