# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_bestarticle_bestcomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('parent_comment', 'reported_by'), ('parent_article', 'reported_by')]),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('parent_comment', 'created_by'), ('parent_article', 'created_by')]),
        ),
    ]
