# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-27 07:52
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180620_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['en_name']),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['en_name']),
        ),
    ]
