# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180727_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.TextField(default='', verbose_name='이름'),
            preserve_default=False,
        ),
    ]
