# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20180410_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationReadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('is_read', models.BooleanField(default=False, verbose_name='조회 여부')),
            ],
            options={
                'verbose_name': '알림 조회 기록',
                'verbose_name_plural': '알림 조회 기록',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='', verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='related_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_set', to='core.Article', verbose_name='알림 관련 제보'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_set', to='core.Comment', verbose_name='알림 관련 댓글'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('default', 'default'), ('article_commented', 'article_commented'), ('comment_commented', 'comment_commented')], default='default', max_length=32, verbose_name='알림 종류'),
        ),
        migrations.AddField(
            model_name='notificationreadlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_log_set', to='core.Notification', verbose_name='관련 알림'),
        ),
        migrations.AddField(
            model_name='notificationreadlog',
            name='read_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_log_set', to=settings.AUTH_USER_MODEL, verbose_name='관련 사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationreadlog',
            unique_together=set([('read_by', 'notification', 'deleted_at')]),
        ),
    ]
