# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20180428_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDeleteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('deleted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='삭제된 시간')),
            ],
            options={
                'verbose_name': '게시물 삭제 기록',
                'verbose_name_plural': '게시물 삭제 기록',
            },
        ),
        migrations.CreateModel(
            name='CommentDeleteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('deleted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='삭제된 시간')),
            ],
            options={
                'verbose_name': '댓글 삭제 기록',
                'verbose_name_plural': '댓글 삭제 기록',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
        migrations.AddField(
            model_name='commentdeletelog',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_delete_log_set', to='core.Comment', verbose_name='삭제된 댓글'),
        ),
        migrations.AddField(
            model_name='commentdeletelog',
            name='deleted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_delete_log_set', to=settings.AUTH_USER_MODEL, verbose_name='삭제자'),
        ),
        migrations.AddField(
            model_name='articledeletelog',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_delete_log_set', to='core.Article', verbose_name='삭제된 게시글'),
        ),
        migrations.AddField(
            model_name='articledeletelog',
            name='deleted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_delete_log_set', to=settings.AUTH_USER_MODEL, verbose_name='삭제자'),
        ),
    ]
