# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('content', models.TextField(default=None, verbose_name='본문')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명')),
                ('is_content_sexual', models.BooleanField(default=False, verbose_name='성인/음란성 내용')),
                ('is_content_social', models.BooleanField(default=False, verbose_name='정치/사회성 내용')),
                ('use_signature', models.BooleanField(default=True, verbose_name='서명 사용')),
                ('positive_vote_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('negative_vote_count', models.IntegerField(default=0, verbose_name='싫어요 수')),
                ('attachment', models.ImageField(default=None, upload_to='', verbose_name='첨부 그림')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent_article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='core.Article', verbose_name='글')),
                ('parent_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='core.Comment', verbose_name='댓글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
            },
        ),
    ]
