# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180429_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
    ]
