# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('content', models.TextField(default=None, verbose_name='본문')),
                ('attachment', models.ImageField(default=None, upload_to='', verbose_name='첨부 그림')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_update_log_set', to='core.Comment', verbose_name='변경된 댓글')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_update_log_set', to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
            ],
            options={
                'verbose_name': '댓글 변경 기록',
                'verbose_name_plural': '댓글 변경 기록',
            },
        ),
    ]
