# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180429_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledeletelog',
            name='deleted_time',
        ),
        migrations.RemoveField(
            model_name='commentdeletelog',
            name='deleted_time',
        ),
    ]
