# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20180501_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(default=None, null=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_set', to=settings.AUTH_USER_MODEL, verbose_name='차단한 사람')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_set', to=settings.AUTH_USER_MODEL, verbose_name='차단당한 사람')),
            ],
            options={
                'verbose_name': '차단',
                'verbose_name_plural': '차단',
            },
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='black_from',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='black_to',
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
