# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commentupdatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleupdatelog',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_update_log_set', to=settings.AUTH_USER_MODEL, verbose_name='변경자'),
        ),
    ]
