# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180501_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestarticle',
            name='best_by',
            field=models.CharField(choices=[('positive_vote_count', 'positive_vote_count'), ('hit_count', 'hit_count')], default='positive_vote_count', max_length=32, verbose_name='베스트 문서 선정 기준'),
        ),
        migrations.AddField(
            model_name='bestarticle',
            name='period',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly')], default='daily', max_length=32, verbose_name='베스트 문서 종류'),
        ),
    ]
