# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171026_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_content_sexual',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_content_social',
        ),
    ]
