# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180501_1724'),
        ('core', '0009_auto_20180501_1706'),
    ]

    operations = [
    ]
