# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20180501_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commented_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='마지막 댓글 시간'),
        ),
    ]
