# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_article_commented_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_status',
            field=models.CharField(default='-', max_length=10, verbose_name='읽음 상태'),
        ),
    ]
