# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_blacklist'),
        ('core', '0009_auto_20171026_2135'),
    ]

    operations = [
    ]
