# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-02 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180511_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='articledeletelog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='articledeletelog',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='articledeletelog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='articlereadlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='articlereadlog',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='articlereadlog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='articleupdatelog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='articleupdatelog',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='articleupdatelog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='bestarticle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='bestarticle',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='bestarticle',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='bestcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='bestcomment',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='bestcomment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='block',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='block',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='board',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='board',
            name='en_name',
            field=models.CharField(max_length=32, verbose_name='게시판 영문 이름'),
        ),
        migrations.AlterField(
            model_name='board',
            name='ko_name',
            field=models.CharField(max_length=32, verbose_name='게시판 국문 이름'),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='commentdeletelog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='commentdeletelog',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='commentdeletelog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='commentupdatelog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='commentupdatelog',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='commentupdatelog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='notificationreadlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='notificationreadlog',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='notificationreadlog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='en_name',
            field=models.CharField(max_length=32, verbose_name='말머리 영문 이름'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='ko_name',
            field=models.CharField(max_length=32, verbose_name='말머리 국문 이름'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='삭제 시간'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='수정 시간'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('ko_name', 'deleted_at'), ('en_name', 'deleted_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('ko_name', 'deleted_at'), ('en_name', 'deleted_at')]),
        ),
    ]
