# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-10 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180602_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_status',
        ),
    ]
