# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 01:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_remove_article_read_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='created_by',
            new_name='voted_by',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('parent_comment', 'voted_by', 'deleted_at'), ('parent_article', 'voted_by', 'deleted_at')]),
        ),
    ]
