# Generated by Django 4.2.5 on 2023-11-09 13:13

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="제목")),
                ("content", models.TextField(verbose_name="본문")),
                ("started_at", models.DateTimeField(verbose_name="모달 노출 시작 시간")),
                ("expired_at", models.DateTimeField(verbose_name="모달 노출 종료 시간")),
            ],
            options={
                "verbose_name": "글로벌 공지",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
