# Generated by Django 4.2.11 on 2025-03-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=256)),
                ("content", models.TextField()),
                ("prev_post_id", models.BigIntegerField(blank=True, null=True)),
                ("next_post_id", models.BigIntegerField(blank=True, null=True)),
                ("board_id", models.IntegerField()),
                ("group_id", models.IntegerField()),
                ("group_level", models.IntegerField()),
                ("group_count", models.IntegerField()),
                ("is_deleted", models.BooleanField()),
                ("is_public", models.BooleanField()),
                ("attachment_count", models.SmallIntegerField()),
                ("view_count", models.SmallIntegerField()),
                ("writer_id", models.CharField(max_length=32)),
                ("writer_name", models.CharField(max_length=32)),
                (
                    "writer_department",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "writer_email",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("registered_at", models.DateTimeField()),
                ("registered_user_id", models.CharField(max_length=32)),
                ("changed_at", models.DateTimeField()),
                ("changed_user_id", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
