# Generated by Django 4.2.20 on 2025-03-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kaist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="registered_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
