# Generated by Django 4.2.23 on 2025-11-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaist', '0002_alter_post_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViewCountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(help_text='기록 시점의 조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_count_logs', to='kaist.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='kaist_postv_post_id_22f681_idx')],
            },
        ),
    ]
