# Generated by Django 4.2.23 on 2025-11-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaist', '0003_postviewcountlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board_name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
