# Generated by Django 4.2.23 on 2025-11-29 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_comment_type'),
        ('kaist', '0004_post_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ara_article',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaist_posts', to='core.article'),
        ),
    ]
