# Generated by Django 5.2.11 on 2026-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaist', '0005_post_ara_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviewcountlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
