# Generated by Django 4.2.23 on 2025-11-06 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(db_index=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='삭제 시간')),
                ('menu_name', models.TextField(verbose_name='메뉴명')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='가격')),
                ('date', models.DateField(verbose_name='날짜')),
                ('day', models.CharField(max_length=16, verbose_name='요일')),
                ('time', models.CharField(max_length=16, verbose_name='시간대(조식/중식/석식)')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(db_index=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='삭제 시간')),
                ('restaurant_name', models.CharField(max_length=32, verbose_name='식당 이름')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='가격')),
                ('date', models.DateField(verbose_name='날짜')),
                ('day', models.CharField(max_length=16, verbose_name='요일')),
                ('time', models.CharField(max_length=16, verbose_name='시간대(조식/중식/석식)')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(db_index=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='삭제 시간')),
                ('menu_name', models.TextField(blank=True, null=True, verbose_name='메뉴명')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_set', to='meal.course', verbose_name='코스')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(db_index=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='삭제 시간')),
                ('allergen_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='알러지 번호')),
                ('cafeteria_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_set', to='meal.cafeteriamenu', verbose_name='카페테리아 메뉴')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_set', to='meal.menu', verbose_name='일반 메뉴')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
