# Generated by Django 4.2.23 on 2025-11-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteriamenu',
            name='day',
        ),
        migrations.RemoveField(
            model_name='cafeteriamenu',
            name='time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AddField(
            model_name='cafeteriamenu',
            name='meal_time',
            field=models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=10, null=True, verbose_name='식사 시간대'),
        ),
        migrations.AddField(
            model_name='course',
            name='meal_time',
            field=models.CharField(choices=[(0, 'BREAKFAST'), (1, 'LUNCH'), (2, 'DINNER')], max_length=10, null=True, verbose_name='식사 시간대'),
        ),
        migrations.AlterField(
            model_name='menuallergy',
            name='cafeteria_menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergy_set', to='meal.cafeteriamenu', verbose_name='카페테리아 메뉴'),
        ),
        migrations.AlterField(
            model_name='menuallergy',
            name='menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergy_set', to='meal.menu', verbose_name='일반 메뉴'),
        ),
    ]
