# Generated by Django 4.2.23 on 2025-11-25 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_remove_cafeteriamenu_day_remove_cafeteriamenu_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(db_index=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='삭제 시간')),
                ('restaurant_name', models.CharField(max_length=32, unique=True, verbose_name='식당 이름')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default=str, max_length=32, verbose_name='코스 이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='meal_time',
            field=models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=10, null=True, verbose_name='식사 시간대'),
        ),
        migrations.AddField(
            model_name='cafeteriamenu',
            name='restaurant_id',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_menus', to='meal.restaurant', verbose_name='식당 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='restaurant_id',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='meal.restaurant', verbose_name='식당 이름'),
            preserve_default=False,
        ),
    ]
