# Generated by Django 5.2.13 on 2026-09-25 11:04

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0004_alter_cafeteriamenu_id_alter_course_id_alter_menu_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "BREAKFAST"),
                            ("LUNCH", "LUNCH"),
                            ("DINNER", "DINNER"),
                        ],
                        max_length=10,
                        verbose_name="식사 시간대",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="meal/menu_photos", verbose_name="사진"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="한 줄 후기",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("USER", "USER"), ("INSTAGRAM", "INSTAGRAM")],
                        default="USER",
                        max_length=20,
                        verbose_name="출처",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="올린 사람",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_photos",
                        to="meal.restaurant",
                        verbose_name="식당",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["restaurant", "date", "meal_time"],
                        name="menu_photo_meal",
                    )
                ],
            },
        ),
    ]
