# Generated by Django 5.2.13 on 2026-09-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0005_menuphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="code",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="학교 사이트 코드",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="운영 중"),
        ),
    ]
