# Generated by Django 5.2.13 on 2026-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0006_restaurant_code_restaurant_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="표시 이름"
            ),
        ),
    ]
