# Generated by Django 5.2.13 on 2026-09-26 12:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0007_restaurant_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="업체 이름")),
                (
                    "intro",
                    models.TextField(blank=True, default="", verbose_name="소개"),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("EAST", "EAST"),
                            ("WEST", "WEST"),
                            ("NORTH", "NORTH"),
                        ],
                        max_length=10,
                        verbose_name="구역",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="위치 (건물 / 상세)",
                    ),
                ),
                (
                    "hours",
                    models.JSONField(blank=True, default=dict, verbose_name="영업시간"),
                ),
                (
                    "hours_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="영업시간 메모",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="meal/stores",
                        verbose_name="대표 이미지",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="전화번호"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="링크"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="운영 중"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stores",
                        to="meal.restaurant",
                        verbose_name="속한 식당",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("CLOSED", "CLOSED"), ("OPEN", "OPEN")],
                        max_length=10,
                        verbose_name="종류",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="시작")),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="끝"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="사유"
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="임시 영업 시작"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="임시 영업 끝"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="meal.store",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="분류"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="메뉴 이름")),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="가격"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="설명"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="meal/store_menus",
                        verbose_name="사진",
                    ),
                ),
                (
                    "is_sold_out",
                    models.BooleanField(default=False, verbose_name="품절"),
                ),
                (
                    "is_signature",
                    models.BooleanField(default=False, verbose_name="대표 메뉴"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="meal.store",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("body", models.TextField(blank=True, default="", verbose_name="내용")),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="끝"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="meal.store",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="meal.store",
                        verbose_name="업체",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="직원 계정",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "unique_together": {("store", "user", "deleted_at")},
            },
        ),
    ]
