# Generated by Django 5.2.13 on 2026-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0008_store_storeevent_storemenu_storenotice_storestaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="분류"
            ),
        ),
    ]
