# Generated by Django 5.2.13 on 2026-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0009_store_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuphoto",
            name="source_post_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="원본 게시물 id",
            ),
        ),
    ]
