# Generated by Django 5.2.13 on 2026-09-26 18:37

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0010_menuphoto_source_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storemenu",
            name="section",
        ),
        migrations.CreateModel(
            name="StoreMenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_categories",
                        to="meal.store",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "unique_together": {("store", "name", "deleted_at")},
            },
        ),
        migrations.AddField(
            model_name="storemenu",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menus",
                to="meal.storemenucategory",
                verbose_name="카테고리",
            ),
        ),
    ]
