# Generated by Django 4.2.6 on 2023-11-16 15:42

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("is_allday", models.BooleanField(default=False, verbose_name="하루종일")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="시작 시간"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="종료 시간"
                    ),
                ),
                ("ko_title", models.CharField(max_length=512, verbose_name="한글 제목")),
                ("en_title", models.CharField(max_length=512, verbose_name="영어 제목")),
                (
                    "ko_description",
                    models.CharField(max_length=512, verbose_name="한글 설명"),
                ),
                (
                    "en_description",
                    models.CharField(max_length=512, verbose_name="영어 설명"),
                ),
                ("location", models.CharField(max_length=512, verbose_name="위치")),
                (
                    "url",
                    models.URLField(
                        blank=True, default=None, null=True, verbose_name="포탈 링크"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calendar.calendar",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="calendar",
            name="tags",
            field=models.ManyToManyField(related_name="calendars", to="calendar.tag"),
        ),
    ]
