# Generated by Django 4.2.6 on 2023-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
