from .env import env

# https://wiki.sparcs.org/w/index.php/SPARCS_SSO

SSO_CLIENT_ID = env("SSO_CLIENT_ID")

SSO_SECRET_KEY = env("SSO_SECRET_KEY")

PORTAL_ID = env("PORTAL_ID")

PORTAL_PASSWORD = env("PORTAL_PASSWORD")

PORTAL_2FA_KEY = env("PORTAL_2FA_KEY")

PORTAL_JSESSIONID = env("PORTAL_JSESSIONID")
