[fcgi-program:asgi]
socket=tcp://localhost:9000
command=venv/bin/daphne -u /run/daphne/daphne%(process_num)d.sock --fd 0 --access-log - --proxy-headers ara.asgi:application
numprocs=3
process_name=asgi%(process_num)d
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery-beat]
command = /newara/www/venv/bin/celery -A ara beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/newara/www
stdout_logfile=/var/log/newara/celery-beat.log
stderr_logfile=/var/log/newara/celery-beat.log
