# Generated by Django 4.2.23 on 2025-07-03 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "message_id",
                    models.PositiveIntegerField(
                        default=None, null=True, verbose_name="메시지 ID"
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="메시지 만료 시점"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "room_id",
                    models.PositiveIntegerField(
                        db_index=True, default=0, unique=True, verbose_name="room_id"
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("DM", "DM"),
                            ("GROUP_DM", "GROUP_DM"),
                            ("OPEN_CHAT", "OPEN_CHAT"),
                        ],
                        default="OPEN_CHAT",
                        max_length=20,
                        verbose_name="room_type",
                    ),
                ),
                (
                    "chat_name_type",
                    models.CharField(
                        choices=[
                            ("NICKNAME", "NICKNAME"),
                            ("ANONYMOUS", "ANONYMOUS"),
                            ("REAL_NAME", "REAL_NAME"),
                        ],
                        default="NICKNAME",
                        max_length=20,
                        verbose_name="chat_name_type",
                    ),
                ),
                (
                    "recent_message_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="recent_message_at"
                    ),
                ),
                (
                    "recent_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recent_for_room",
                        to="chatting.chatmessage",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpiredChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "message_id",
                    models.PositiveIntegerField(
                        default=None, null=True, verbose_name="메시지 ID"
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expired_message_set",
                        to="chatting.chatroom",
                        verbose_name="메시지가 속한 채팅방",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expired_message_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="메시지 작성자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatRoomPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "room_delete_permission",
                    models.CharField(
                        choices=[
                            ("ALL", "전체"),
                            ("ADMIN", "관리자 이상"),
                            ("OWNER", "소유자만"),
                            ("PARTICIPANT", "참여자 이상"),
                        ],
                        default="OWNER",
                        max_length=20,
                        verbose_name="채팅방 삭제 권한",
                    ),
                ),
                (
                    "chat_room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_permission",
                        to="chatting.chatroom",
                        verbose_name="권한이 적용될 채팅방",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatRoomMemberShip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "OWNER"),
                            ("ADMIN", "ADMIN"),
                            ("PARTICIPANT", "PARTICIPANT"),
                            ("OBSERVER", "OBSERVER"),
                            ("BLOCKED", "BLOCKED"),
                            ("BLOCKER", "BLOCKER"),
                        ],
                        default="PARTICIPANT",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="last_seen_at"
                    ),
                ),
                (
                    "subscribed",
                    models.BooleanField(
                        default=True, null=True, verbose_name="subscribed"
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_info_set",
                        to="chatting.chatroom",
                        verbose_name="chat_room",
                    ),
                ),
                (
                    "last_seen_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_last_seen_message",
                        to="chatting.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_participant_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User 정보",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatRoomInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "invitation_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "OWNER"),
                            ("ADMIN", "ADMIN"),
                            ("PARTICIPANT", "PARTICIPANT"),
                            ("OBSERVER", "OBSERVER"),
                        ],
                        default="PARTICIPANT",
                        max_length=20,
                        verbose_name="초대받은 User의 Role",
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="초대장 만료 일시"
                    ),
                ),
                (
                    "invitation_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inviting_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="초대한 유저의 ID",
                    ),
                ),
                (
                    "invitation_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="초대받은 유저의 ID",
                    ),
                ),
                (
                    "invited_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_set",
                        to="chatting.chatroom",
                        verbose_name="초대된 채팅방",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chat_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_set",
                to="chatting.chatroom",
                verbose_name="메시지가 속한 채팅방",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="메시지 작성자",
            ),
        ),
        migrations.AddConstraint(
            model_name="expiredchatmessage",
            constraint=models.UniqueConstraint(
                fields=("chat_room", "message_id"),
                name="unique_chatroom_expired_messageid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroommembership",
            constraint=models.UniqueConstraint(
                fields=("chat_room", "user"), name="unique_chatroom_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(
                fields=("chat_room", "message_id"), name="unique_chatroom_messageid"
            ),
        ),
    ]
