# Generated by Django 4.2.23 on 2025-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="message_content",
            field=models.TextField(default="", verbose_name="메시지 본문"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "TEXT"),
                    ("IMAGE", "IMAGE"),
                    ("FILE", "FILE"),
                    ("EMOTICON", "EMOTICON"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="message_type",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="room_title",
            field=models.CharField(
                default="아라 채팅방", max_length=100, verbose_name="채팅방 이름"
            ),
        ),
        migrations.AddField(
            model_name="chatroompermission",
            name="entrance_permission",
            field=models.CharField(
                choices=[("ALL", "전체"), ("INVITED", "초대받은 사용자만")],
                default="INVITED",
                max_length=20,
                verbose_name="입장 권한",
            ),
        ),
        migrations.AddField(
            model_name="chatroompermission",
            name="invite_permission",
            field=models.CharField(
                choices=[
                    ("ALL", "전체"),
                    ("ADMIN", "관리자 이상"),
                    ("OWNER", "소유자만"),
                ],
                default="ALL",
                max_length=20,
                verbose_name="초대 권한",
            ),
        ),
        migrations.AddField(
            model_name="chatroompermission",
            name="kick_permission",
            field=models.CharField(
                choices=[
                    ("ALL", "전체"),
                    ("ADMIN", "관리자 이상"),
                    ("OWNER", "소유자만"),
                    ("PARTICIPANT", "참여자 이상"),
                ],
                default="ALL",
                max_length=20,
                verbose_name="유저 강퇴 권한",
            ),
        ),
        migrations.AddField(
            model_name="chatroompermission",
            name="message_permission",
            field=models.CharField(
                choices=[
                    ("ALL", "전체"),
                    ("ADMIN", "관리자 이상"),
                    ("OWNER", "소유자만"),
                    ("PARTICIPANT", "참여자 이상"),
                ],
                default="ALL",
                max_length=20,
                verbose_name="메세지 보내기 권한",
            ),
        ),
        migrations.AddField(
            model_name="chatroompermission",
            name="permission_update_permmission",
            field=models.CharField(
                choices=[
                    ("ALL", "전체"),
                    ("ADMIN", "관리자 이상"),
                    ("OWNER", "소유자만"),
                ],
                default="OWNER",
                max_length=20,
                verbose_name="권한 업데이트 권한",
            ),
        ),
        migrations.AddField(
            model_name="expiredchatmessage",
            name="message_content",
            field=models.TextField(default="", verbose_name="메시지 본문"),
        ),
        migrations.AddField(
            model_name="expiredchatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "TEXT"),
                    ("IMAGE", "IMAGE"),
                    ("FILE", "FILE"),
                    ("EMOTICON", "EMOTICON"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="message_type",
            ),
        ),
    ]
