# Generated by Django 4.2.23 on 2025-07-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chatting",
            "0002_chatmessage_message_content_chatmessage_message_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroompermission",
            name="kick_permission",
            field=models.CharField(
                choices=[
                    ("ALL", "전체"),
                    ("ADMIN", "관리자 이상"),
                    ("OWNER", "소유자만"),
                    ("PARTICIPANT", "참여자 이상"),
                ],
                default="ADMIN",
                max_length=20,
                verbose_name="유저 강퇴 권한",
            ),
        ),
    ]
