# Generated by Django 4.2.23 on 2025-07-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0003_alter_chatroompermission_kick_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroommembership",
            name="subscribed",
            field=models.BooleanField(
                default=False, null=True, verbose_name="subscribed"
            ),
        ),
    ]
