# Generated by Django 4.2.23 on 2025-07-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0005_remove_chatroom_room_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroommembership",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="chatroommembership",
            name="unique_chatroom_user",
        ),
    ]
