# Generated by Django 4.2.23 on 2025-07-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0006_alter_chatroommembership_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="chatmessage",
            name="unique_chatroom_messageid",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="message_id",
        ),
    ]
