# Generated by Django 4.2.23 on 2025-08-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0008_chatroom_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommembership',
            name='last_seen_message',
            field=models.ForeignKey(
                to='chatting.chatmessage',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_last_seen_message',
                verbose_name=None,
            ),
        ),
    ]
