# Generated by Django 5.2.13 on 2026-09-24 15:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0010_alter_chatmessage_id_alter_chatroom_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroommembership",
            name="anon_number",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="익명 번호"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="메시지 작성자",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "TEXT"),
                    ("IMAGE", "IMAGE"),
                    ("FILE", "FILE"),
                    ("EMOTICON", "EMOTICON"),
                    ("VOTE", "VOTE"),
                    ("PAYMENT_REQUEST", "PAYMENT_REQUEST"),
                    ("DELIVERY_ORDER", "DELIVERY_ORDER"),
                    ("DELIVERY_ARRIVAL", "DELIVERY_ARRIVAL"),
                    ("SYSTEM", "SYSTEM"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="message_type",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("DM", "DM"),
                    ("GROUP_DM", "GROUP_DM"),
                    ("OPEN_CHAT", "OPEN_CHAT"),
                    ("DELIVERY", "DELIVERY"),
                ],
                default="OPEN_CHAT",
                max_length=20,
                verbose_name="room_type",
            ),
        ),
        migrations.AlterField(
            model_name="chatroominvitation",
            name="invitation_role",
            field=models.CharField(
                choices=[
                    ("OWNER", "OWNER"),
                    ("ADMIN", "ADMIN"),
                    ("PARTICIPANT", "PARTICIPANT"),
                ],
                default="PARTICIPANT",
                max_length=20,
                verbose_name="초대받은 User의 Role",
            ),
        ),
        migrations.AlterField(
            model_name="chatroommembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "OWNER"),
                    ("ADMIN", "ADMIN"),
                    ("PARTICIPANT", "PARTICIPANT"),
                    ("BLOCKED", "BLOCKED"),
                    ("BLOCKER", "BLOCKER"),
                ],
                default="PARTICIPANT",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="expiredchatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "TEXT"),
                    ("IMAGE", "IMAGE"),
                    ("FILE", "FILE"),
                    ("EMOTICON", "EMOTICON"),
                    ("VOTE", "VOTE"),
                    ("PAYMENT_REQUEST", "PAYMENT_REQUEST"),
                    ("DELIVERY_ORDER", "DELIVERY_ORDER"),
                    ("DELIVERY_ARRIVAL", "DELIVERY_ARRIVAL"),
                    ("SYSTEM", "SYSTEM"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="message_type",
            ),
        ),
        migrations.CreateModel(
            name="ChatPaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("bank_name", models.CharField(max_length=30, verbose_name="은행")),
                (
                    "account_number",
                    models.CharField(max_length=30, verbose_name="계좌번호"),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_request",
                        to="chatting.chatmessage",
                        verbose_name="정산 요청 메시지",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="투표 제목")),
                (
                    "max_choices",
                    models.PositiveSmallIntegerField(
                        blank=True, default=1, null=True, verbose_name="최대 선택 수"
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote",
                        to="chatting.chatmessage",
                        verbose_name="투표 메시지",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatVoteOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("text", models.CharField(max_length=100, verbose_name="선택지 내용")),
                ("order", models.PositiveSmallIntegerField(verbose_name="선택지 순서")),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="chatting.chatvote",
                        verbose_name="투표",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatPaymentTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="송금할 금액")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="송금 완료 시각",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="chatting.chatpaymentrequest",
                        verbose_name="정산 요청",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_payment_targets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="송금할 유저",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "unique_together": {("request", "user", "deleted_at")},
            },
        ),
        migrations.CreateModel(
            name="ChatVoteBallot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_vote_ballots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="투표한 유저",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballots",
                        to="chatting.chatvoteoption",
                        verbose_name="선택지",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "unique_together": {("option", "user", "deleted_at")},
            },
        ),
    ]
