# Generated by Django 5.2.13 on 2026-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0011_chatroommembership_anon_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatpaymentrequest",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="취소 시각"
            ),
        ),
    ]
