# Generated by Django 5.2.13 on 2026-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0012_chatpaymentrequest_canceled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatpaymenttarget",
            name="delivery_fee_share",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="배송비 몫"
            ),
        ),
        migrations.AddField(
            model_name="chatpaymenttarget",
            name="order_amount",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="주문 금액"
            ),
        ),
    ]
