# Generated by Django 5.2.13 on 2026-09-25 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0013_chatpaymenttarget_delivery_fee_share_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat_room", "deleted_at", "id"],
                name="chat_msg_room_deleted_id",
            ),
        ),
    ]
