# Generated by Django 5.2.13 on 2026-09-25 14:48

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0014_chatmessage_chat_msg_room_deleted_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="수정 시간"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="삭제 시간",
                    ),
                ),
                (
                    "reported_anon_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="피신고자 익명 번호"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("violation_of_code", "violation_of_code"),
                            ("impersonation", "impersonation"),
                            ("insult", "insult"),
                            ("spam", "spam"),
                            ("others", "others"),
                        ],
                        max_length=128,
                        verbose_name="신고 사유",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="내용"),
                ),
                (
                    "reporter_email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="신고자 이메일 (신고 시점)",
                    ),
                ),
                (
                    "reported_email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="피신고자 이메일 (신고 시점)",
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_set",
                        to="chatting.chatroom",
                        verbose_name="채팅방",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_set",
                        to="chatting.chatmessage",
                        verbose_name="신고된 메시지",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reports_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="피신고자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 신고",
                "verbose_name_plural": "채팅 신고 목록",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
